DROP TABLE IF EXISTS gpa_terms;
DROP TABLE IF EXISTS yellow_card_subjects;
DROP TABLE IF EXISTS student_profiles;

ALTER TABLE users DROP COLUMN IF EXISTS student_id;
ALTER TABLE users DROP COLUMN IF EXISTS name;
ALTER TABLE users DROP COLUMN IF EXISTS role;
ALTER TABLE users DROP COLUMN IF EXISTS major;
ALTER TABLE users DROP COLUMN IF EXISTS minor;
ALTER TABLE users DROP COLUMN IF EXISTS curriculum;
ALTER TABLE users DROP COLUMN IF EXISTS pdpa_agreed;
ALTER TABLE users DROP COLUMN IF EXISTS updated_at;

ALTER TABLE users ALTER COLUMN id TYPE UUID USING id::uuid;
